[package]
name = "text_tree"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"

[dependencies]
nom = "6"
tracing = "0.1.22"

[dev-dependencies]
tracing-subscriber = "0.2"
structopt = "0.3"